#!/usr/bin/env node

const fs = require("fs");
const path = require("path");
const { loadAllTokens, resolveTokenValue } = require("./token-utils");

const ROOT_DIR = path.resolve(__dirname, "..");
const OUTPUT_PATH = path.join(ROOT_DIR, "css", "custom-properties.css");

function getTokenValue(tokens, tokenPath) {
  return resolveTokenValue(tokens, tokenPath);
}

const FLAT_COLOR_KEYS = [
  "brand-primary",
  "brand-secondary",
  "brand-dark",
  "accent",
  "focus-button",
  "light-purple",
  "soft-lavender",
  "lavender-official",
  "light-green",
  "light-orange",
  "pink",
  "teal",
  "purple",
  "very-light-gray",
  "light-gray",
  "teal-deep",
  "magenta",
  "navy",
  "blush",
  "yellow",
  "red",
  "warm-grey-light",
  "warm-grey",
  "theme-1",
  "theme-2",
  "theme-4",
  "theme-5",
  "theme-7",
  "theme-8",
];

const SEMANTIC_COLOR_KEYS = [
  "background-default",
  "background-soft",
  "background-title",
  "background-alert",
  "accent-icon",
  "accent-border",
  "focus-ring",
  "focus-visible-accent",
];

const COLOR_RAMPS = {
  neutral: ["50", "100", "200", "300", "400", "500", "600", "700", "800", "900"],
  orange: ["50", "100", "150", "200", "300", "400", "500", "600", "700", "800", "900"],
  green: ["50", "100", "150", "200", "300", "400", "500", "600", "700", "800", "900"],
  blue: ["50", "100", "150", "200", "300", "400", "500", "600", "700", "800", "900"],
  lavender: ["50", "100", "150", "200", "300", "400", "500", "600", "700", "800", "900"],
};

const SPACING_KEYS = [
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "8",
  "10",
  "12",
  "14",
  "16",
  "18",
  "20",
  "22",
  "24",
  "26",
  "28",
  "30",
  "32",
];

function buildCss(tokens) {
  const colorCss = FLAT_COLOR_KEYS.map(
    (key) =>
      `  --color-${key}: ${getTokenValue(tokens, `color.${key}`)};`,
  ).join("\n");

  const semanticColorCss = SEMANTIC_COLOR_KEYS.map(
    (key) => `  --color-${key}: ${getTokenValue(tokens, `color.${key}`)};`,
  ).join("\n");

  const rampCss = Object.entries(COLOR_RAMPS)
    .map(([family, steps]) => {
      const lines = steps
        .map(
          (step) =>
            `  --color-${family}-${step}: ${getTokenValue(tokens, `color.${family}.${step}`)};`,
        )
        .join("\n");
      return `  /* ${family} */\n${lines}`;
    })
    .join("\n\n");

  const spacingCss = SPACING_KEYS.map(
    (key) => `  --spacing-${key}: ${getTokenValue(tokens, `spacing.${key}`)};`,
  ).join("\n");

  return `/* ==========================================================================
   ForEveryone Berlin — Design Tokens
   AUTO-GENERATED by scripts/build-css.js — do not edit manually
   Source of truth: tokens/*.json
   ========================================================================== */

:root {

  /* ── Colors: Brand ─────────────────────────────────────────────────────── */
${colorCss}

  /* ── Colors: Semantic (2026 brand guide) ─────────────────────────────── */
  /* Use these instead of raw brand colors for backgrounds and accents.    */
  /* --color-brand-primary (orange) is DECORATIVE ONLY — never a bg.       */
${semanticColorCss}

  /* ── Colors: Status ──────────────────────────────────────────────────── */
  --color-status-error:   ${getTokenValue(tokens, "color.status.error")};
  --color-status-success: ${getTokenValue(tokens, "color.status.success")};
  --color-status-warning: ${getTokenValue(tokens, "color.status.warning")};

  /* ── Colors: Base ────────────────────────────────────────────────────── */
  --color-white: ${getTokenValue(tokens, "color.base.white")};
  --color-black: ${getTokenValue(tokens, "color.base.black")};

  /* ── Colors: PRINT / DOC — NOT FOR DIGITAL UI ────────────────────────── */
  /* Emitted for the /print reference page and print-mock surfaces only.    */
  /* Do NOT reference these from shipped digital components. Print purple    */
  /* substitutes Brand Blue in CMYK; doc greys are Brand Book document       */
  /* chrome, not part of the brand palette. (Brand Book v1.0 p.17)           */
  --color-print-purple-home:  ${getTokenValue(tokens, "color.print.purple-home")};
  --color-print-purple-press: ${getTokenValue(tokens, "color.print.purple-press")};
  --color-doc-grey-light:     ${getTokenValue(tokens, "color.doc.grey-light")};
  --color-doc-grey-dark:      ${getTokenValue(tokens, "color.doc.grey-dark")};

  /* ── Colors: Ramps (2026 style guide, 50–900) ───────────────────────── */
  /* Numeric tints for prototype/web surfaces. 500 = brand "main" for       */
  /* orange/green/blue/lavender; neutral 900 = Charcoal. Orange stays        */
  /* DECORATIVE ONLY — never a text background.                              */
${rampCss}

  /* ── Typography: Font Families ───────────────────────────────────────── */
  --font-family-heading: ${getTokenValue(tokens, "font.family.heading")};
  /* PRINT-ONLY. Do not reference --font-family-accent from digital surfaces. */
  --font-family-accent:  ${getTokenValue(tokens, "font.family.accent")};
  --font-family-body:    ${getTokenValue(tokens, "font.family.body")};

  /* ── Typography: Font Weights ────────────────────────────────────────── */
  --font-weight-regular: ${getTokenValue(tokens, "font.weight.regular")};
  --font-weight-italic:  ${getTokenValue(tokens, "font.weight.italic")};  /* STYLE: pair with font-style: italic */
  --font-weight-medium:  ${getTokenValue(tokens, "font.weight.medium")};
  --font-weight-medium-italic: ${getTokenValue(tokens, "font.weight.medium-italic")};  /* STYLE: 500 + font-style: italic */
  --font-weight-bold:    ${getTokenValue(tokens, "font.weight.bold")};
  --font-weight-bold-italic: ${getTokenValue(tokens, "font.weight.bold-italic")};  /* STYLE: 700 + font-style: italic */

  /* ── Typography: Font Sizes ──────────────────────────────────────────── */
  --font-size-xs:   ${getTokenValue(tokens, "font.size.xs")};   /* 12px — tags, labels */
  --font-size-sm:   ${getTokenValue(tokens, "font.size.sm")};  /* 14px */
  --font-size-base: ${getTokenValue(tokens, "font.size.base")};      /* 16px — body, inputs, buttons */
  --font-size-lg:   ${getTokenValue(tokens, "font.size.lg")};   /* 18px */
  --font-size-xl:   ${getTokenValue(tokens, "font.size.xl")};   /* 20px — H3 */
  --font-size-2xl:  ${getTokenValue(tokens, "font.size.2xl")};  /* 24px */
  --font-size-3xl:  ${getTokenValue(tokens, "font.size.3xl")};      /* 48px — H2 section headers */
  --font-size-4xl:  ${getTokenValue(tokens, "font.size.4xl")};   /* 84px — H1 hero */

  /* ── Typography: Line Heights ────────────────────────────────────────── */
  --line-height-tight:  ${getTokenValue(tokens, "font.lineHeight.tight")};   /* H1 */
  --line-height-snug:   ${getTokenValue(tokens, "font.lineHeight.snug")};   /* H2, H3, tags */
  --line-height-normal: ${getTokenValue(tokens, "font.lineHeight.normal")};   /* body, inputs, buttons */

  /* ── Typography: Letter Spacing ──────────────────────────────────────── */
  --letter-spacing-tight:  ${getTokenValue(tokens, "font.letterSpacing.tight")};  /* headings */
  --letter-spacing-normal:  ${getTokenValue(tokens, "font.letterSpacing.normal")};     /* body/UI */

  /* ── Spacing ─────────────────────────────────────────────────────────── */
${spacingCss}

  /* ── Border Radius ───────────────────────────────────────────────────── */
  --radius-sm:     ${getTokenValue(tokens, "radius.sm")};
  --radius-md:     ${getTokenValue(tokens, "radius.md")};
  --radius-lg:     ${getTokenValue(tokens, "radius.lg")};
  --radius-xl:     ${getTokenValue(tokens, "radius.xl")};
  --radius-card:   ${getTokenValue(tokens, "radius.card")};   /* workshop cards */
  --radius-pill:   ${getTokenValue(tokens, "radius.pill")}; /* buttons, tags */
  --radius-circle: ${getTokenValue(tokens, "radius.circle")};    /* icon buttons, avatar blobs */

  /* ── Shadows ─────────────────────────────────────────────────────────── */
  --shadow-sm:   ${getTokenValue(tokens, "shadow.sm")};
  --shadow-md:   ${getTokenValue(tokens, "shadow.md")};
  --shadow-lg:   ${getTokenValue(tokens, "shadow.lg")};
  --shadow-card:   ${getTokenValue(tokens, "shadow.card")};  /* workshop card */
  --shadow-header: ${getTokenValue(tokens, "shadow.header")};

  /* ── Motion ──────────────────────────────────────────────────────────── */
  --transition-fast: ${getTokenValue(tokens, "motion.transition.fast")};
  --transition-base: ${getTokenValue(tokens, "motion.transition.base")};
  --transition-slow: ${getTokenValue(tokens, "motion.transition.slow")};

  /* ── Layout ──────────────────────────────────────────────────────────── */
  --container-max-width: 1280px;
  --section-padding-y-desktop: var(--spacing-20);  /* 80px */
  --section-padding-y-mobile:  var(--spacing-12);  /* 48px */
  --section-padding-x-desktop: var(--spacing-8);
  --section-padding-x-mobile:  var(--spacing-4);
}
`;
}

function main() {
  const tokens = loadAllTokens();
  const css = buildCss(tokens);
  fs.writeFileSync(OUTPUT_PATH, css, "utf8");
  console.log(`Generated ${path.relative(ROOT_DIR, OUTPUT_PATH)}`);
}

main();
