#!/usr/bin/env node

const fs = require("fs");
const path = require("path");

const ROOT_DIR = path.resolve(__dirname, "..");
const TOKENS_DIR = path.join(ROOT_DIR, "tokens");
const INDEX_PATH = path.join(TOKENS_DIR, "index.json");
const OUTPUT_PATH = path.join(ROOT_DIR, "css", "custom-properties.css");

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}

function isPlainObject(value) {
  return value && typeof value === "object" && !Array.isArray(value);
}

function deepMerge(target, source) {
  const result = { ...target };
  for (const [key, value] of Object.entries(source)) {
    if (isPlainObject(value) && isPlainObject(result[key])) {
      result[key] = deepMerge(result[key], value);
    } else {
      result[key] = value;
    }
  }
  return result;
}

function getTokenValue(tokens, tokenPath) {
  const segments = tokenPath.split(".");
  let current = tokens;
  for (const segment of segments) {
    if (!current || !(segment in current)) {
      throw new Error(`Missing token path: ${tokenPath}`);
    }
    current = current[segment];
  }

  if (!current || typeof current !== "object" || !("$value" in current)) {
    throw new Error(`Invalid token leaf at path: ${tokenPath}`);
  }
  return current.$value;
}

function loadAllTokens() {
  const index = readJson(INDEX_PATH);
  const imports = index.imports || [];
  if (!Array.isArray(imports) || imports.length === 0) {
    throw new Error("tokens/index.json must define a non-empty imports array.");
  }

  let merged = {};
  for (const relativePath of imports) {
    const fullPath = path.resolve(TOKENS_DIR, relativePath);
    const json = readJson(fullPath);
    merged = deepMerge(merged, json);
  }
  return merged;
}

function buildCss(tokens) {
  return `/* ==========================================================================
   ForEveryone Berlin — Design Tokens
   AUTO-GENERATED by scripts/build-css.js — do not edit manually
   Source of truth: tokens/*.json
   ========================================================================== */

:root {

  /* ── Colors: Primary (Orange) ─────────────────────────────────────────── */
  --color-primary-50:   ${getTokenValue(tokens, "color.primary.50")};
  --color-primary-300:  ${getTokenValue(tokens, "color.primary.300")};
  --color-primary-500:  ${getTokenValue(tokens, "color.primary.500")};  /* Orange_main */
  --color-primary-600:  ${getTokenValue(tokens, "color.primary.600")};
  --color-primary-900:  ${getTokenValue(tokens, "color.primary.900")};

  /* ── Colors: Secondary ───────────────────────────────────────────────── */
  --color-secondary-blue-400:     ${getTokenValue(tokens, "color.secondary.blue.400")};
  --color-secondary-blue-500:     ${getTokenValue(tokens, "color.secondary.blue.500")};  /* Blue_main */
  --color-secondary-lavender-400: ${getTokenValue(tokens, "color.secondary.lavender.400")};  /* footer/card bg */
  --color-secondary-lavender-500: ${getTokenValue(tokens, "color.secondary.lavender.500")};
  --color-secondary-green-500:    ${getTokenValue(tokens, "color.secondary.green.500")};  /* Green_main */

  /* ── Colors: Neutral ─────────────────────────────────────────────────── */
  --color-neutral-50:   ${getTokenValue(tokens, "color.neutral.50")};
  --color-neutral-100:  ${getTokenValue(tokens, "color.neutral.100")};
  --color-neutral-200:  ${getTokenValue(tokens, "color.neutral.200")};
  --color-neutral-300:  ${getTokenValue(tokens, "color.neutral.300")};
  --color-neutral-400:  ${getTokenValue(tokens, "color.neutral.400")};
  --color-neutral-500:  ${getTokenValue(tokens, "color.neutral.500")};
  --color-neutral-600:  ${getTokenValue(tokens, "color.neutral.600")};
  --color-neutral-700:  ${getTokenValue(tokens, "color.neutral.700")};
  --color-neutral-800:  ${getTokenValue(tokens, "color.neutral.800")};
  --color-neutral-900:  ${getTokenValue(tokens, "color.neutral.900")};  /* Neutral_main — default text */
  --color-neutral-1000: ${getTokenValue(tokens, "color.neutral.1000")};

  /* ── Colors: Status ──────────────────────────────────────────────────── */
  --color-status-error:   ${getTokenValue(tokens, "color.status.error")};
  --color-status-success: ${getTokenValue(tokens, "color.status.success")};
  --color-status-warning: ${getTokenValue(tokens, "color.status.warning")};

  /* ── Colors: Base ────────────────────────────────────────────────────── */
  --color-white: ${getTokenValue(tokens, "color.base.white")};
  --color-black: ${getTokenValue(tokens, "color.base.black")};

  /* ── Typography: Font Families ───────────────────────────────────────── */
  --font-family-heading: ${getTokenValue(tokens, "font.family.heading")};
  --font-family-accent:  ${getTokenValue(tokens, "font.family.accent")};
  --font-family-body:    ${getTokenValue(tokens, "font.family.body")};

  /* ── Typography: Font Weights ────────────────────────────────────────── */
  --font-weight-regular: ${getTokenValue(tokens, "font.weight.regular")};
  --font-weight-medium:  ${getTokenValue(tokens, "font.weight.medium")};
  --font-weight-bold:    ${getTokenValue(tokens, "font.weight.bold")};
  --font-weight-black:   ${getTokenValue(tokens, "font.weight.black")};

  /* ── Typography: Font Sizes ──────────────────────────────────────────── */
  --font-size-xs:   ${getTokenValue(tokens, "font.size.xs")};   /* 12px — tags, labels */
  --font-size-sm:   ${getTokenValue(tokens, "font.size.sm")};  /* 14px */
  --font-size-base: ${getTokenValue(tokens, "font.size.base")};      /* 16px — body, inputs, buttons */
  --font-size-xl:   ${getTokenValue(tokens, "font.size.xl")};   /* 20px — H3 */
  --font-size-3xl:  ${getTokenValue(tokens, "font.size.3xl")};      /* 48px — H2 section headers */
  --font-size-4xl:  ${getTokenValue(tokens, "font.size.4xl")};   /* 84px — H1 hero */

  /* ── Typography: Line Heights ────────────────────────────────────────── */
  --line-height-tight:  ${getTokenValue(tokens, "font.lineHeight.tight")};   /* H1 */
  --line-height-snug:   ${getTokenValue(tokens, "font.lineHeight.snug")};   /* H2, H3, tags */
  --line-height-normal: ${getTokenValue(tokens, "font.lineHeight.normal")};   /* body, inputs, buttons */

  /* ── Typography: Letter Spacing ──────────────────────────────────────── */
  --letter-spacing-tight:  ${getTokenValue(tokens, "font.letterSpacing.tight")};  /* headings */
  --letter-spacing-normal:  ${getTokenValue(tokens, "font.letterSpacing.normal")};     /* body/UI */

  /* ── Spacing ─────────────────────────────────────────────────────────── */
  --spacing-1:  ${getTokenValue(tokens, "spacing.1")};   /* 4px  */
  --spacing-2:  ${getTokenValue(tokens, "spacing.2")};    /* 8px  */
  --spacing-3:  ${getTokenValue(tokens, "spacing.3")};   /* 12px */
  --spacing-4:  ${getTokenValue(tokens, "spacing.4")};      /* 16px */
  --spacing-5:  ${getTokenValue(tokens, "spacing.5")};   /* 20px */
  --spacing-6:  ${getTokenValue(tokens, "spacing.6")};    /* 24px */
  --spacing-8:  ${getTokenValue(tokens, "spacing.8")};      /* 32px */
  --spacing-10: ${getTokenValue(tokens, "spacing.10")};    /* 40px */
  --spacing-12: ${getTokenValue(tokens, "spacing.12")};      /* 48px */
  --spacing-16: ${getTokenValue(tokens, "spacing.16")};      /* 64px */
  --spacing-20: ${getTokenValue(tokens, "spacing.20")};      /* 80px */
  --spacing-24: ${getTokenValue(tokens, "spacing.24")};      /* 96px */

  /* ── Border Radius ───────────────────────────────────────────────────── */
  --radius-sm:     ${getTokenValue(tokens, "radius.sm")};
  --radius-md:     ${getTokenValue(tokens, "radius.md")};
  --radius-lg:     ${getTokenValue(tokens, "radius.lg")};
  --radius-xl:     ${getTokenValue(tokens, "radius.xl")};
  --radius-card:   ${getTokenValue(tokens, "radius.card")};   /* workshop cards */
  --radius-pill:   ${getTokenValue(tokens, "radius.pill")}; /* buttons, tags */
  --radius-circle: ${getTokenValue(tokens, "radius.circle")};    /* icon buttons, avatar blobs */

  /* ── Shadows ─────────────────────────────────────────────────────────── */
  --shadow-sm:   ${getTokenValue(tokens, "shadow.sm")};
  --shadow-md:   ${getTokenValue(tokens, "shadow.md")};
  --shadow-lg:   ${getTokenValue(tokens, "shadow.lg")};
  --shadow-card: ${getTokenValue(tokens, "shadow.card")};  /* workshop card */

  /* ── Motion ──────────────────────────────────────────────────────────── */
  --transition-fast: ${getTokenValue(tokens, "motion.transition.fast")};
  --transition-base: ${getTokenValue(tokens, "motion.transition.base")};
  --transition-slow: ${getTokenValue(tokens, "motion.transition.slow")};

  /* ── Layout ──────────────────────────────────────────────────────────── */
  --container-max-width: 1280px;
  --section-padding-y-desktop: var(--spacing-20);  /* 80px */
  --section-padding-y-mobile:  var(--spacing-12);  /* 48px */
  --section-padding-x-desktop: var(--spacing-8);
  --section-padding-x-mobile:  var(--spacing-4);
}
`;
}

function main() {
  const tokens = loadAllTokens();
  const css = buildCss(tokens);
  fs.writeFileSync(OUTPUT_PATH, css, "utf8");
  console.log(`Generated ${path.relative(ROOT_DIR, OUTPUT_PATH)}`);
}

main();
